### ISSUE TITLE
Issue when cloning: "error: unable to create file .babelrc"

### ISSUE THREAD

**Issue by AllynH** [lassegit/flask-reactjs#1]
Hi there,
Just wanted to touch base and let you know I've found an issue where, when cloning the repo, the .bablerc file fails with an error.
When I do a git status, it looks like there are special characters in the file name:

    git status
    On branch master
    Your branch is up-to-date with 'origin/master'.
    Changes not staged for commit:
      (use "git add/rm <file>..." to update what will be committed)
      (use "git checkout -- <file>..." to discard changes in working directory)
    
            deleted:    ".babelrc\n\n"

So it looks like the .bablerc file has `\n\n` added to the name.

**Comment by lassegit** [comment]
You are right, there seem to be some linebreaks in the filename. I have fixed it. Thanks.
